In [1]:
#Importing necessary library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\ML Project\WebApp\spam.csv")
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.shape

(5572, 2)

In [5]:
data['Message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [8]:
data['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [10]:
data['spam'] = data['Category'].apply(lambda x: 1 if x == 'spam' else 0)
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
import seaborn as sns

In [17]:
data.duplicated().sum()

415

In [18]:
data.drop_duplicates(inplace=True)

In [19]:
data.duplicated().sum()

0

In [20]:
data.isnull().sum()

Category    0
Message     0
spam        0
dtype: int64

In [21]:
data.shape

(5157, 3)

In [22]:
data['spam'].value_counts()

0    4516
1     641
Name: spam, dtype: int64

# Separate in X and Y

In [24]:
X = data['Message'].values
y = data['spam'].values

In [25]:
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

# Train - Test split

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state= 0)

In [27]:
X_train.shape

(4125,)

In [28]:
X_test.shape

(1032,)

In [29]:
y_train.shape

(4125,)

In [30]:
y_test.shape

(1032,)

# Preprocessing 

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
cv = CountVectorizer()


# Training by ML Algorithm

In [33]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
nb = MultinomialNB()

In [34]:
pipe = make_pipeline(cv, nb)

In [35]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [36]:
y_pred = pipe.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9864341085271318

In [38]:
email = ['Hey i am Elon Musk. Get a brand new car from Tesla']
pipe.predict(email)

array([0], dtype=int64)

In [39]:
import pickle
pickle.dump(pipe, open("Naive_model.pkl",'wb'))

# Testing

In [42]:
emails = ['Hey i am Elon Musk. Get a brand new car from Tesla',
    'hey mohan, we can get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. dont miss this reward!',
    'No 1 POLYPHONIC tone 4 ur mob every week! Just txt PT2 to 87575. 1st Tone FREE ! so get txtin now and tell ur friends. 150p/tone. 16 reply HL 4info',
    'lyricalladie(21/F) is inviting you to be her friend. Reply YES-910 or NO-910. See her: www.SMS.ac/u/hmmross STOP? Send STOP FRND to 62468'
]
pipe.predict(emails)

array([0, 0, 1, 1, 1], dtype=int64)